### ISSUE TITLE
Error in x[seq_len(n)] : object of type 'S4' is not subsettable

### ISSUE THREAD

**Issue by jhyhy0825** [shangll123/SpatialPCA#1]
Hi, I was creating SpatialPCA object using the raw count data and location coordinates.
I used the code "ST = CreateSpatialPCAObject(counts=rawcount, location=location, project = "SpatialPCA",gene.type="spatial",sparkversion="spark", gene.number=3000,customGenelist=NULL,min.loctions = 20, min.features=20)" and there is an error below.

Using top  3000  significant spatially variable genes. 
Error in x[seq_len(n)] : object of type 'S4' is not subsettable
Calls: head -> head.default
Execution halted

If you know the reason, please reply.

Thank you.

**Comment by shangll123** [comment]
We appreciate your interest in our package. Could you provide additional details regarding this error message? This is the first time I've encountered such a message, and I'd like to fix it in case others encounter similar issues. Would it be possible for you to send me a copy of your data (shanglu [at] umich.edu) or put it in some public google folder, so I can replicate the error and assist you in debugging it? Thank you!
