### ISSUE TITLE
Running Spatial PCA on Gaussian data

### ISSUE THREAD

**Issue by william-denault** [shangll123/SpatialPCA#12]
Hello,

I am interested in running spatial PCA on some spatial factor model to assess its de-noising property.

The model is LF^T +E , where E is a Gaussian noise. I am running different experiment with different noise level. My understanding is that the current implement assumes a certain level of variance of each row (1 I suspect).

Do you have any suggestion on how to run spatial PCA on some Gaussian data. See an R example below. I would like to run spatial PCA on Z.

`x <-runif(1000)
y <-runif(1000)
X = cbind(x,y)
plot (x,y) 
library(ggplot2) 
 

set.seed(3)#problem fro set.seed(1)
f <- matrix(NA, nrow = 3, ncol =200)
for ( i in 1:ncol (f)){
  
  t1<- sample (c(0,1), size=1)
  t2<- sample (c(0,1), size=1)
  
  f[1,i] <- t1*rnorm(n=1)
  f[2,i] <- t2*rnorm(n=1)
  
  f[3,i] <- t2*rnorm(n=1)
  
}
L <- matrix(NA, ncol=3, nrow=length(x))

factor  <- c()

for (i in 1:length(x)){
  
  if ( (x[i] <.33 & y[i] <.33 )|(x[i] >.33 & y[i] >.33 &  x[i] <.66 & y[i] <.66) | (x[i] >.66 & y[i] >.66 )){
    L[i,] <- c(1,0,0)
    factor=c(factor,1)
  }else{
    if ( (x[i] <.33 & y[i] >.66 )|(x[i] >.33 & y[i] <.33 &  x[i] <.66  ) | (x[i] >.66 & y[i] >.33  & y[i] <.66)){
      L[i,] <- c(0,1,0)
      factor=c(factor,2)
    }else{
      L[i,] <- c(0,0,1)
      factor=c(factor,3)
    }
  }
  
  
}

df = data.frame(x=x,y=y, Factor=as.factor(factor))

colors <- c("#D41159","#1A85FF","#40B0A6" )
P1 <- ggplot(df, aes(x,y, col=Factor))+geom_point(size=3)+
  
  geom_hline(yintercept = 0.33)+
  geom_hline(yintercept = 0.66)+
  geom_vline(xintercept = 0.66)+
  geom_vline(xintercept = 0.33)+
  xlab("")+ylab("")+
  scale_color_manual(values = colors)+
  theme_minimal()+theme( axis.text.y=element_blank(),
                         
                         axis.ticks.y=element_blank(),
                         axis.text.x=element_blank(),
                         axis.ticks.x=element_blank())

Z = L%*%f + matrix(rnorm(nrow(L)* ncol(f), sd=2), nrow = nrow(L))
`

**Comment by shangll123** [comment]
The data inputs for SpatialPCA are two matrices, the gene expression matrix (gene_num x location_num) and spatial coordinate matrix (location_num x d). I suspect you will need to figure out which one is the gene expression matrix and spatial coordinate matrix in your data, and then you can try to run SpatialPCA on that.
