### ISSUE TITLE
Downloadable link

### ISSUE THREAD

**Issue by SoichiroA** [shangll123/SpatialPCA#13]
Hello,
Thank you for sharing this great package!
On the tutorial homepage, I found that all links to google drive are expired/invalid anymore.
https://lulushang.org/SpatialPCA_Tutorial/Vizgen.html

Can I ask you to replace this with new ones?

**Comment by shangll123** [comment]
Thank you for letting me know, here is the new link: https://drive.google.com/drive/folders/1Ibz5uNsFKHJ4roPpaec5nPL_EBF3-wxY?usp=share_link. We also updated all links on the tutorial. 

Best,
Lulu
