### ISSUE TITLE
When I run the step 'CreateSpatialPCAObject', the cell count of DLPFC151510 changed from 4634 to 4633.

### ISSUE THREAD

**Issue by cowwcat** [shangll123/SpatialPCA#14]
When running with both the data downloaded from the LIBD and the data you provided, this situation occurred. There were no issues with other datasets. I'm curious to understand why this is happening and if there's a solution. Looking forward to your assistance.
![20240530164152](https://github.com/shangll123/SpatialPCA/assets/116610876/c243b700-88eb-4956-9a79-0e5e7d1ddbae)

**Comment by shangll123** [comment]
Hello,

This is because we have filtering steps embedded within this function. We filtered out genes expressed in less than 20 locations, and locations with less than 20 genes expressed (details in the paper). Hope this helps.

Best,
Lulu
