### ISSUE TITLE
Using spatial PCA to project new data 

### ISSUE THREAD

**Issue by emathian** [shangll123/SpatialPCA#4]
Hello :)

I found your work fascinating. That's why I want to use it on a very different problem which is to use your spatial PCA on encoded vectors which are the outputs of a neural network. Our number of points (i.e. n) is very large. So I applied your method to a subsample of our data set. Now I want to project the remaining element onto the latent space defined by W. One solution would be:
$Z_{proj} = W^{-1}(Y_{proj} - (XB)^T)$
Another solution would be to reuse equation 13 of your supplementary methods. What would be your solution?
Many thanks in advance!

**Comment by shangll123** [comment]
Thank you for your interest in our paper! We are working on developing a new version of SpatialPCA which might solve the problem you have, will post it on GitHub once we finish it. Thank you for your patience!

Best,
Lulu
