### ISSUE TITLE
SpatialPCA with Stereo-Seq data

### ISSUE THREAD

**Issue by tvegawaichman** [shangll123/SpatialPCA#5]
Hello! I'm working with Stereo-seq data, specifically with the MOSTA dataset.
I want to know which parameters you would recommend for running this kind of dataset.
I have been using the parameters from Slide-seq V2, but I'm unsure if they are the most accurate.
Thanks!

**Comment by shangll123** [comment]
Hello! Thanks for your interest in our method! I just tried SpatialPCA on one example sample from MOSTA, the parameters from SlideseqV2 works well there. Please refer to the newly created tutorial here: [https://lulushang.org/docs/Projects/SpatialPCA/MOSTA](https://lulushang.org/docs/Projects/SpatialPCA/MOSTA), and please feel free to let me know if the link doesn't work. Hope this helps!

Best,
Lulu

**Comment by tvegawaichman** [comment]
This is very useful! Thanks for the quick reply!

**Comment by shangll123** [comment]
Sure thing!
