### ISSUE TITLE
Error in tutorial

### ISSUE THREAD

**Issue by newmana** [shangll123/SpatialPCA#9]
Hi,

I can't find the source for the "Breast Tumor" tutorial but I believe there is an error in either the code or the documentation:
![image](https://github.com/shangll123/SpatialPCA/assets/22402/79bebd3a-e743-42ae-9373-1aca1e0c3094)

Should the code be using Louvian clustering instead? Or should the documentation say it's using walktrap?

https://lulushang.org/SpatialPCA_Tutorial/ST.html

**Comment by shangll123** [comment]
Hi,

Thank you for your interest in our method. We applied the Walktrap method to the small datasets (DLPFC and ST tumor) and due to its heavy computational burden applied the Louvain method to the other two large datasets. 

Best,
Lulu

**Comment by newmana** [comment]
Hi, what I'm saying is the text says "Here we use louvian's clustering method" and the code is using walktrap.

**Comment by shangll123** [comment]
Oh I see! Yes it should be walktrap, thanks for pointing this out!
